#application: ecole-autonome
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: src/static/css
  
- url: /fonts
  static_dir: src/static/fonts
  
- url: /js
  static_dir: src/static/js
  
- url: /images
  static_dir: src/static/images
  
- url: /
  script: src.main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
